<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="10" passed="7" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-09T15:23:34Z" name="Suite" finished-at="2024-03-09T15:24:27Z" duration-ms="53134">
    <groups>
    </groups>
    <test started-at="2024-03-09T15:23:34Z" name="Test" finished-at="2024-03-09T15:24:27Z" duration-ms="53134">
      <class name="com.crm.qa.testcases.Transactiontest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.crm.qa.testcases.Transactiontest@6d167f58]" started-at="2024-03-09T20:54:16Z" name="setUp" finished-at="2024-03-09T20:54:19Z" duration-ms="2311" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCustomerActions()[pri:0, instance:com.crm.qa.testcases.Transactiontest@6d167f58]" started-at="2024-03-09T20:54:19Z" name="testCustomerActions" finished-at="2024-03-09T20:54:21Z" duration-ms="2725" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCustomerActions -->
      </class> <!-- com.crm.qa.testcases.Transactiontest -->
      <class name="com.crm.qa.testcases.Openaccount">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.crm.qa.testcases.Openaccount@c7ba306]" started-at="2024-03-09T20:54:07Z" name="setUp" finished-at="2024-03-09T20:54:09Z" duration-ms="2372" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testOpenAccount()[pri:0, instance:com.crm.qa.testcases.Openaccount@c7ba306]" started-at="2024-03-09T20:54:09Z" name="testOpenAccount" finished-at="2024-03-09T20:54:12Z" duration-ms="2084" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOpenAccount -->
      </class> <!-- com.crm.qa.testcases.Openaccount -->
      <class name="com.crm.qa.testcases.invcustomertest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.crm.qa.testcases.invcustomertest@1f53a5dc]" started-at="2024-03-09T20:53:39Z" name="setUp" finished-at="2024-03-09T20:53:41Z" duration-ms="2516" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="invadd()[pri:0, instance:com.crm.qa.testcases.invcustomertest@1f53a5dc]" started-at="2024-03-09T20:53:41Z" name="invadd" finished-at="2024-03-09T20:53:44Z" duration-ms="2309" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error message is not displayed for invalid data expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error message is not displayed for invalid data expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at com.crm.qa.testcases.invcustomertest.invadd(invcustomertest.java:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invadd -->
      </class> <!-- com.crm.qa.testcases.invcustomertest -->
      <class name="com.crm.qa.testcases.deletetest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.crm.qa.testcases.deletetest@1b75c2e3]" started-at="2024-03-09T20:53:44Z" name="setUp" finished-at="2024-03-09T20:53:47Z" duration-ms="3188" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testBankCustomer()[pri:0, instance:com.crm.qa.testcases.deletetest@1b75c2e3]" started-at="2024-03-09T20:53:47Z" name="testBankCustomer" finished-at="2024-03-09T20:53:49Z" duration-ms="2221" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBankCustomer -->
      </class> <!-- com.crm.qa.testcases.deletetest -->
      <class name="com.crm.qa.testcases.withdrawvalidtest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.crm.qa.testcases.withdrawvalidtest@3403e2ac]" started-at="2024-03-09T20:54:21Z" name="setUp" finished-at="2024-03-09T20:54:24Z" duration-ms="2547" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCustomerActions()[pri:0, instance:com.crm.qa.testcases.withdrawvalidtest@3403e2ac]" started-at="2024-03-09T20:54:24Z" name="testCustomerActions" finished-at="2024-03-09T20:54:27Z" duration-ms="3390" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCustomerActions -->
      </class> <!-- com.crm.qa.testcases.withdrawvalidtest -->
      <class name="com.crm.qa.testcases.Deposittest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.crm.qa.testcases.Deposittest@1984b1f]" started-at="2024-03-09T20:53:49Z" name="setUp" finished-at="2024-03-09T20:53:51Z" duration-ms="2403" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCustomerActions()[pri:0, instance:com.crm.qa.testcases.Deposittest@1984b1f]" started-at="2024-03-09T20:53:51Z" name="testCustomerActions" finished-at="2024-03-09T20:53:56Z" duration-ms="4111" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCustomerActions -->
      </class> <!-- com.crm.qa.testcases.Deposittest -->
      <class name="com.crm.qa.testcases.Invwithdrawtest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.crm.qa.testcases.Invwithdrawtest@39ac0c0a]" started-at="2024-03-09T20:54:01Z" name="setUp" finished-at="2024-03-09T20:54:03Z" duration-ms="2425" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCustomerActions()[pri:0, instance:com.crm.qa.testcases.Invwithdrawtest@39ac0c0a]" started-at="2024-03-09T20:54:03Z" name="testCustomerActions" finished-at="2024-03-09T20:54:07Z" duration-ms="3758" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Alert message not as expected expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Alert message not as expected expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at com.crm.qa.testcases.Invwithdrawtest.testCustomerActions(Invwithdrawtest.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCustomerActions -->
      </class> <!-- com.crm.qa.testcases.Invwithdrawtest -->
      <class name="com.crm.qa.testcases.invdeposittest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.crm.qa.testcases.invdeposittest@3bd323e9]" started-at="2024-03-09T20:53:56Z" name="setUp" finished-at="2024-03-09T20:53:58Z" duration-ms="2182" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testCustomerActions()[pri:0, instance:com.crm.qa.testcases.invdeposittest@3bd323e9]" started-at="2024-03-09T20:53:58Z" name="testCustomerActions" finished-at="2024-03-09T20:54:01Z" duration-ms="3213" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Alert message not as expected expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Alert message not as expected expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at com.crm.qa.testcases.invdeposittest.testCustomerActions(invdeposittest.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCustomerActions -->
      </class> <!-- com.crm.qa.testcases.invdeposittest -->
      <class name="com.crm.qa.testcases.Addcustomer">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.crm.qa.testcases.Addcustomer@413f69cc]" started-at="2024-03-09T20:53:34Z" name="setUp" finished-at="2024-03-09T20:53:37Z" duration-ms="2617" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="addcustest()[pri:0, instance:com.crm.qa.testcases.Addcustomer@413f69cc]" started-at="2024-03-09T20:53:37Z" name="addcustest" finished-at="2024-03-09T20:53:39Z" duration-ms="1973" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addcustest -->
      </class> <!-- com.crm.qa.testcases.Addcustomer -->
      <class name="com.crm.qa.testcases.Searchcustomer">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.crm.qa.testcases.Searchcustomer@4ff8d125]" started-at="2024-03-09T20:54:12Z" name="setUp" finished-at="2024-03-09T20:54:14Z" duration-ms="2847" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testBankCustomer()[pri:0, instance:com.crm.qa.testcases.Searchcustomer@4ff8d125]" started-at="2024-03-09T20:54:14Z" name="testBankCustomer" finished-at="2024-03-09T20:54:16Z" duration-ms="1911" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBankCustomer -->
      </class> <!-- com.crm.qa.testcases.Searchcustomer -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
